In [1]:
import pandas as pd

df = pd.read_csv("cars.csv")

In [5]:
#1

df.duplicated().sum()

np.int64(715)

Empty DataFrame
Columns: [Make, Model, Year, Engine Fuel Type, Engine HP, Engine Cylinders, Transmission Type, Driven_Wheels, Number of Doors, Market Category, Vehicle Size, Vehicle Style, highway MPG, city mpg, Popularity, MSRP, Average MPG]
Index: []

In [6]:
#2

df = df.drop_duplicates()

In [7]:
#3

df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [8]:
#4

df.groupby("Make")["MSRP"].mean().round().sort_values(ascending=False).head(10)

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          238219.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

In [9]:
#5

df.groupby("Make")["MSRP"].mean().round().sort_values(ascending=False).head(10)

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          238219.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

In [10]:
#6

df.groupby("Year")["MSRP"].mean().round()

Year
1990     2032.0
1991     2119.0
1992     2108.0
1993     2245.0
1994     2394.0
1995     2700.0
1996     2567.0
1997     3165.0
1998     3036.0
1999     3154.0
2000     3197.0
2001    41501.0
2002    33744.0
2003    39774.0
2004    36107.0
2005    36747.0
2006    32075.0
2007    35278.0
2008    56754.0
2009    50404.0
2010    52021.0
2011    57570.0
2012    61959.0
2013    51476.0
2014    65523.0
2015    47506.0
2016    47864.0
2017    42185.0
Name: MSRP, dtype: float64

In [11]:
#7

df["Average MPG"] = (df["city mpg"] + df["highway MPG"]) / 2

df.groupby("Year")[["Engine HP", "Average MPG"]].mean().round()

      Engine HP  Average MPG
Year
1990      144.0         20.0
1991      151.0         20.0
1992      148.0         22.0
1993      155.0         22.0
1994      157.0         21.0
1995      177.0         20.0
1996      174.0         21.0
1997      185.0         19.0
1998      194.0         19.0
1999      191.0         20.0
2000      185.0         21.0
2001      194.0         21.0
2002      196.0         20.0
2003      206.0         20.0
2004      215.0         20.0
2005      219.0         20.0
2006      229.0         20.0
2007      253.0         19.0
2008      261.0         20.0
2009      254.0         21.0
2010      253.0         21.0
2011      263.0         22.0
2012      272.0         22.0
2013      277.0         24.0
2014      298.0         25.0
2015      274.0         25.0
2016      276.0         25.0
2017      275.0         25.0

In [12]:
#8 

df["Vehicle Size"].value_counts(normalize=True).mul(100).round(2)

Vehicle Size
Compact    39.24
Midsize    36.80
Large      23.96
Name: proportion, dtype: float64

In [14]:
#9

df["Vehicle Style"].value_counts()

Vehicle Style
Sedan                  2843
4dr SUV                2434
Coupe                  1175
Convertible             741
4dr Hatchback           663
Crew Cab Pickup         655
Extended Cab Pickup     597
Wagon                   562
2dr Hatchback           412
Passenger Minivan       389
Regular Cab Pickup      345
Passenger Van           121
2dr SUV                  91
Cargo Van                84
Cargo Minivan            59
Convertible SUV          28
Name: count, dtype: int64

In [17]:
df["Vehicle Style"].value_counts().head() #for only the top ones

Vehicle Style
Sedan            2843
4dr SUV          2434
Coupe            1175
Convertible       741
4dr Hatchback     663
Name: count, dtype: int64

In [18]:
#10

df[(df["MSRP"] >= 40000) & (df["Popularity"] >= 1000)]["Make"].value_counts()

Make
Cadillac       354
BMW            269
Audi           224
Chevrolet      216
Ford           145
Porsche        123
Toyota         120
Nissan          91
Ferrari         69
Dodge           55
Lamborghini     52
Chrysler        18
Tesla           18
Kia             17
Honda           14
Hyundai         13
Name: count, dtype: int64

In [19]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP', 'Average MPG'],
      dtype='object')