In [3]:
import pandas as pd

df = pd.read_csv("cars.csv")

In [4]:
#1

df.duplicated().sum()

df[df.duplicated()]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

In [5]:
#2

df = df.drop_duplicates()

In [6]:
#3

df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [7]:
#4

df = df.dropna()

In [8]:
#5

df.groupby("Make")["MSRP"].mean().round().sort_values(ascending=False).head(10)

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          237384.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

In [9]:
#6

df.groupby("Year")["MSRP"].mean().round()

Year
1990     2073.0
1991     2223.0
1992     2192.0
1993     2401.0
1994     2726.0
1995     3270.0
1996     3140.0
1997     4524.0
1998     4434.0
1999     3612.0
2000     3913.0
2001    73833.0
2002    55704.0
2003    68312.0
2004    55908.0
2005    53724.0
2006    39001.0
2007    41173.0
2008    80462.0
2009    59193.0
2010    60152.0
2011    65663.0
2012    71837.0
2013    55201.0
2014    71196.0
2015    52613.0
2016    52580.0
2017    45333.0
Name: MSRP, dtype: float64

In [11]:
#7

df["Average MPG"] = (df["city mpg"] + df["highway MPG"]) / 2

df.groupby("Year")[["Engine HP", "Average MPG"]].mean().round()

      Engine HP  Average MPG
Year
1990      154.0         21.0
1991      163.0         21.0
1992      155.0         22.0
1993      174.0         21.0
1994      167.0         21.0
1995      203.0         20.0
1996      201.0         21.0
1997      200.0         21.0
1998      224.0         20.0
1999      199.0         21.0
2000      202.0         21.0
2001      243.0         20.0
2002      244.0         19.0
2003      258.0         19.0
2004      260.0         19.0
2005      255.0         20.0
2006      248.0         20.0
2007      274.0         18.0
2008      298.0         19.0
2009      268.0         20.0
2010      269.0         20.0
2011      280.0         22.0
2012      293.0         22.0
2013      290.0         23.0
2014      311.0         23.0
2015      288.0         24.0
2016      290.0         24.0
2017      285.0         25.0

In [12]:
#8

df["Vehicle Size"].value_counts(normalize=True).mul(100).round(2)

Vehicle Size
Midsize    39.34
Compact    36.81
Large      23.85
Name: proportion, dtype: float64

In [13]:
#9

df["Vehicle Style"].value_counts()

Vehicle Style
4dr SUV                2053
Sedan                  1801
Coupe                   922
Convertible             645
4dr Hatchback           639
2dr Hatchback           409
Wagon                   349
Crew Cab Pickup         334
Extended Cab Pickup     187
Regular Cab Pickup      176
Passenger Van           100
Passenger Minivan        61
Cargo Van                34
2dr SUV                  14
Convertible SUV           6
Cargo Minivan             5
Name: count, dtype: int64

In [14]:
df["Vehicle Style"].value_counts().head()

Vehicle Style
4dr SUV          2053
Sedan            1801
Coupe             922
Convertible       645
4dr Hatchback     639
Name: count, dtype: int64

In [15]:
#10

df[(df["MSRP"] >= 40000) & (df["Popularity"] >= 1000)]["Make"].value_counts()

Make
Cadillac       354
BMW            269
Audi           224
Chevrolet      171
Porsche        123
Ford           105
Nissan          69
Ferrari         68
Lamborghini     52
Toyota          50
Dodge           49
Kia             16
Hyundai         13
Chrysler        12
Honda            8
Name: count, dtype: int64