In [107]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")

In [117]:
query1 = """
SELECT JobTitle,
       AVG(TotalPayBenefits) AS AverageTotalPayBenefits
FROM Salaries
WHERE JobTitle NOT IN ('Not Provided', 'Not provided')
GROUP BY JobTitle
ORDER BY AverageTotalPayBenefits DESC
"""

df1 = pd.read_sql_query(query1, conn)
df1

                                            JobTitle  AverageTotalPayBenefits
0                           Chief Investment Officer            436224.360000
1                                    Chief of Police            411732.266667
2                             Chief, Fire Department            408865.326667
3     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY            399211.275000
4                         Gen Mgr, Public Trnsp Dept            380696.440000
...                                              ...                      ...
2153                           SPECIAL ASSISTANT XIV               673.800000
2154              BOARD/COMMISSION MEMBER, GROUP III               638.787879
2155                      BdComm Mbr, Grp2,M=$25/Mtg               475.047742
2156               BOARD/COMMISSION MEMBER, GROUP II               296.511628
2157         PUBLIC SAFETY COMMUNICATIONS TECHNICIAN               149.510000

[2158 rows x 2 columns]

In [109]:
query2 = """
SELECT EmployeeName, JobTitle, OvertimePay
FROM Salaries
WHERE CAST(OvertimePay AS REAL) > 50000
ORDER BY OvertimePay DESC
"""

df2 = pd.read_sql_query(query2, conn)
df2

            EmployeeName                        JobTitle  OvertimePay
0         Gary Altenberg    Lieutenant, Fire Suppression    220909.48
1          Whitney P Yee                  Deputy Sheriff    196689.18
2      Frederick Binkley       EMT/Paramedic/Firefighter    192424.49
3     Antonio B Santiago                  Deputy Sheriff    173547.73
4          Barry J Bloom                  Deputy Sheriff    173178.23
...                  ...                             ...          ...
2159     Nicholas Donati                Police Officer 3     50060.80
2160         Craig F Tom                      Sergeant 3     50055.88
2161  Michael I Thompson  Battalion Chief, Fire Suppress     50039.97
2162            SARA COE                     FIREFIGHTER     50019.79
2163       Alan L Harvey                     Firefighter     50018.08

[2164 rows x 3 columns]

In [110]:
query3 = """
SELECT COUNT(DISTINCT EmployeeName) AS UniqueEmployees
FROM Salaries
WHERE EmployeeName NOT IN ('Not Provided', 'Not provided')
"""

df3 = pd.read_sql_query(query3, conn)
df3

   UniqueEmployees
0           110808

In [113]:
query4 = """
SELECT EmployeeName, JobTitle, TotalPayBenefits
FROM Salaries
WHERE EmployeeName NOT IN ('Not Provided', 'Not provided')
ORDER BY TotalPayBenefits DESC
LIMIT 10
"""

df4 = pd.read_sql_query(query4, conn)
df4

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

In [114]:
query5 = """
SELECT *
FROM Salaries
ORDER BY TotalPayBenefits DESC
"""

df5 = pd.read_sql_query(query5, conn)
df5

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,110532,David Shinn,Deputy Chief 3,129150.01,0,342802.63,38780.04,471952.64,510732.68,2014,,San Francisco,PT
2,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,,San Francisco,FT
3,110534,William J Coaker Jr.,Chief Investment Officer,257340,0,82313.7,96570.66,339653.70,436224.36,2014,,San Francisco,PT
4,72926,Gregory P Suhr,Chief of Police,319275.01,0,20007.06,86533.21,339282.07,425815.28,2013,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148649,110529,Timothy E Gibson,Police Officer 3,,0,0,-2.73,0.00,-2.73,2013,,San Francisco,
148650,110530,Mark E Laherty,Police Officer 3,,0,0,-8.2,0.00,-8.20,2013,,San Francisco,
148651,110531,David P Kucia,Police Officer 3,,0,0,-33.89,0.00,-33.89,2013,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [115]:
query5 = """
SELECT EmployeeName, TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
"""

df5 = pd.read_sql_query(query5, conn)
df5

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1                David Shinn         510732.68
2                 Amy P Hart         479652.21
3       William J Coaker Jr.         436224.36
4             Gregory P Suhr         425815.28
...                      ...               ...
148648          Not provided              0.00
148649      Timothy E Gibson             -2.73
148650        Mark E Laherty             -8.20
148651         David P Kucia            -33.89
148652             Joe Lopez           -618.13

[148653 rows x 2 columns]