In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('factbook.db')

In [9]:
query1 = """
SELECT cities.name AS city, cities.population
FROM cities
JOIN facts ON cities.facts_id = facts.id
WHERE facts.area > 5000;
"""
pd.read_sql_query(query1, conn)

          city  population
0    Abu Dhabi      942000
1        Dubai     1978000
2      Sharjah      983000
3        Kabul     3097000
4      Algiers     2916000
..         ...         ...
349    Mbabane       66000
350      Sanaa     2419000
351       Aden      784000
352     Lusaka     1802000
353     Harare     1542000

[354 rows x 2 columns]

In [10]:
query2 = """
SELECT cities.name AS capital_city
FROM cities
JOIN facts ON cities.facts_id = facts.id
WHERE cities.capital = 1
  AND facts.death_rate > 2
  AND facts.birth_rate < 20;
"""
pd.read_sql_query(query2, conn)

         capital_city
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

In [11]:
query3 = """
SELECT cities.name AS city, facts.population_growth
FROM cities
JOIN facts ON cities.facts_id = facts.id
WHERE facts.population_growth BETWEEN 1 AND 5
ORDER BY facts.population_growth DESC;
"""
pd.read_sql_query(query3, conn)

          city  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

In [12]:
query4 = """
SELECT facts.name AS country, cities.name AS city
FROM facts
LEFT JOIN cities ON facts.id = cities.facts_id
WHERE facts.name LIKE 'A%'
  AND cities.id IS NULL;
"""
pd.read_sql_query(query4, conn)

                       country  city
0  Ashmore and Cartier Islands  None
1                     Akrotiri  None
2                   Antarctica  None
3                 Arctic Ocean  None
4               Atlantic Ocean  None

In [13]:
query5 = """
SELECT cities.name AS capital_city, facts.death_rate
FROM cities
LEFT JOIN facts ON cities.facts_id = facts.id
WHERE cities.capital = 1;
"""
pd.read_sql_query(query5, conn)

     capital_city  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]